name: Playwright Tests
on:
  push:
    branches: [ main, issue-* ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  
    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps firefox

    - name: Start restful ecommerce service
      run:  docker compose -f ./docker-compose-ecommerce.yml up -d

    - name: Run Playwright Smoke tests
      env:
        BLOB_REPORT_DIR: blob-report/smoke
      run:  npm run test:smoke

    - name: Run Playwright End to End tests
      env:
        BLOB_REPORT_DIR: blob-report/smoke
      run:  npm run test:e2e

    - name: Prepare Playwright reports
      if: ${{ !cancelled() }}
      run: |
        mkdir -p merged-blob-report
        cp blob-report/smoke/*.zip merged-blob-report/ || true
        cp blob-report/e2e/*.zip merged-blob-report/ || true
      
    - name: Merge Playwright reports
      if: ${{ !cancelled() }}
      run: npx playwright merge-reports --reporter html blob-report

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    